### PR TITLE
Update RestController to make it compatible with ZF 2.4.0

### PR DESCRIPTION
**Pull request by weierophinney**
ZF 2.4.0 adds a required `$data` parameter to `AbstractRestfulController::deleteList()`, which `RestController` extends. For 1.1, we must:

- Update the minimum required ZF2 version to 2.4.0.
- Update `RestController::deleteList()` to accept the new parameter, and pass it to the underlying resource.

### CODE REVIEW

**Comment by weierophinney** [comment]
Patch created, but should not be merged until after ZF 2.4.0 is released, and the original dependencies can be re-instated in the `require-dev` section of `composer.json`.

**Comment by TomHAnderson** [comment]
https://github.com/zfcampus/zf-apigility-doctrine/pull/156 will be on hold until ZF 2.4.0

**Comment by kusmierz** [comment]
@TomHAnderson @weierophinney zf 2.4.0 is out, could you merge it, please?

**Comment by weierophinney** [comment]
@kusmierz Patience. It'll happen soon enough.

**Pull request closed without merging**
