### PR TITLE
Getters instead of magic __get in Hal\Entity

### PR DESCRIPTION
**Pull request by Wilt**
In the `Hal\Collection` class the magic `__get` for collection has been deprecated and now the `getCollection` method has to be called instead.
For consistency  would it not be better to also use similar solution for the `Hal\Entity` class.
So `getEntity` and `getId` methods

This pull request is related to https://github.com/zfcampus/zf-hal/pull/99

### CODE REVIEW

**Comment by weierophinney** [comment]
Looks like there's a fatal now; please check the Travis build results.

**Comment by Wilt** [comment]
The fatal error occurs because it is dependent on the changes of https://github.com/zfcampus/zf-hal/pull/99 but as I understood merging this is not an option anyway because of BC issues. 

I could close both...?

**Comment by weierophinney** [comment]
@Wilt If you make the change suggested to zfcampus/zf-hal#99, I'll merge both of these.

**Comment by weierophinney** [comment]
Merged to develop for release with 1.3.0. Thanks, @Wilt !

**Pull request closed without merging**
