### PR TITLE
500 if page size lower than zero

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by weierophinney** [comment]
Have you actually encountered this before, @snapshotpl ?!?! That's bizarre behavior!

**Comment by snapshotpl** [comment]
Can you release this in 1.2.x as hotfix?

**Comment by weierophinney** [comment]
Due to the slight change in behavior, I merged this to develop for release in 1.3.0.

**Comment by snapshotpl** [comment]
@weierophinney here is similar case and you have merge it as hotfix https://github.com/zfcampus/zf-rest/pull/85

**Pull request closed without merging**
